#!/usr/bin/env bash
#
# One-shot setup for the Hermes + Claude Code stack.
#
# Safe to re-run: it never overwrites an existing .env, config.yaml or
# hermes-home/.env, so your edits survive.
#
#   ./setup.sh
#
set -euo pipefail

cd "$(dirname "$0")"

CONFIG_TEMPLATE="./hermes-config.template.yaml"
# Where Hermes keeps its state. Resolved from HERMES_DATA_DIR once .env is
# sourced, so an existing installation can be adopted in place instead of
# starting from an empty directory.
HERMES_HOME=""
SHIM_URL="http://claude-shim:8080/v1"
# The Hermes container runs as this uid; the bind mount must be writable by it.
HERMES_UID=10000
HERMES_GID=10000

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33m !  %s\033[0m\n' "$*"; }
die()  { printf '\033[31m !! %s\033[0m\n' "$*" >&2; exit 1; }
gen_key() { openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

# ---------------------------------------------------------------------------
say "Checking prerequisites"
# ---------------------------------------------------------------------------
command -v docker >/dev/null || die "docker not found"
docker compose version >/dev/null 2>&1 || die "docker compose v2 not found"
echo "docker: $(docker --version)"

# ---------------------------------------------------------------------------
say "Checking .env"
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
  cp .env.example .env
  chmod 600 .env
  warn ".env created from .env.example -- it is not filled in yet."
  echo
  echo "  1. Mint a token on a machine with a browser (NOT on a headless VPS):"
  echo "       claude setup-token"
  echo "  2. Put it in .env as CLAUDE_CODE_OAUTH_TOKEN, on ONE unbroken line."
  echo "  3. Set HERMES_DASHBOARD_BASIC_AUTH_PASSWORD (openssl rand -hex 24)."
  echo "  4. Re-run ./setup.sh"
  echo
  exit 1
fi

# shellcheck disable=SC1091
set -a; . ./.env; set +a

[ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] || die "CLAUDE_CODE_OAUTH_TOKEN is empty in .env (run: claude setup-token)"
[ -n "${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD:-}" ] || die "HERMES_DASHBOARD_BASIC_AUTH_PASSWORD is empty in .env"

# A wrapped paste is the single most common failure here: .env keeps only the
# first line and the token authenticates as invalid while looking correct.
token_len=${#CLAUDE_CODE_OAUTH_TOKEN}
if [ "$token_len" -lt 100 ]; then
  warn "CLAUDE_CODE_OAUTH_TOKEN is only $token_len characters (expected ~108)."
  warn "If your editor wrapped the paste, the rest is on an orphan line and auth will fail with 401."
fi
echo "token length: $token_len"

# Dashboard session cookies are signed with this. Left unset, Hermes generates
# a random per-process key, so every `docker compose restart hermes` silently
# logs you out. Machine-local, generated once, never shipped in the repo.
if [ -z "${HERMES_DASHBOARD_BASIC_AUTH_SECRET:-}" ]; then
  HERMES_DASHBOARD_BASIC_AUTH_SECRET=$(gen_key)
  export HERMES_DASHBOARD_BASIC_AUTH_SECRET
  tmp=$(mktemp)
  grep -v '^HERMES_DASHBOARD_BASIC_AUTH_SECRET=' .env > "$tmp"
  printf '\n# Generated by setup.sh: signs dashboard session cookies.\nHERMES_DASHBOARD_BASIC_AUTH_SECRET=%s\n' "$HERMES_DASHBOARD_BASIC_AUTH_SECRET" >> "$tmp"
  mv "$tmp" .env
  chmod 600 .env
  echo "generated HERMES_DASHBOARD_BASIC_AUTH_SECRET in .env"
fi

HERMES_HOME="${HERMES_DATA_DIR:-./hermes-home}"
echo "data dir: $HERMES_HOME"

# ---------------------------------------------------------------------------
say "Preparing $HERMES_HOME"
# ---------------------------------------------------------------------------
# Order matters: create and chown BEFORE the first `docker compose up`. If the
# bind-mount source does not exist, Docker creates it owned by root, and the
# container (uid 10000) then cannot write its own state.
mkdir -p "$HERMES_HOME"

if [ "$(uname -s)" = "Linux" ]; then
  if [ "$(id -u)" -eq 0 ]; then
    chown -R "$HERMES_UID:$HERMES_GID" "$HERMES_HOME"
  else
    sudo chown -R "$HERMES_UID:$HERMES_GID" "$HERMES_HOME"
  fi
  echo "chowned to $HERMES_UID:$HERMES_GID"
else
  # Docker Desktop (macOS/Windows) maps uids through its VM, so a plain chown
  # to 10000 does not apply the way it does on Linux.
  chmod -R 777 "$HERMES_HOME"
  echo "chmod 777 (Docker Desktop maps uids itself)"
fi

# ---------------------------------------------------------------------------
say "Seeding Hermes config"
# ---------------------------------------------------------------------------
if [ -f "$HERMES_HOME/config.yaml" ]; then
  echo "config.yaml already exists, leaving it alone"
else
  cp "$CONFIG_TEMPLATE" "$HERMES_HOME/config.yaml"
  echo "copied $CONFIG_TEMPLATE -> $HERMES_HOME/config.yaml"
fi

# Hermes reads its own secrets from here. CUSTOM_API_KEY must be non-empty:
# Hermes' OpenAI client requires a key even though claude-shim ignores it (the
# shim is only reachable on the internal docker network). API_SERVER_KEY is a
# real secret and is generated per deployment, never shipped in the repo.
if [ -f "$HERMES_HOME/.env" ]; then
  # Adopting an existing installation: add only the keys that are missing and
  # never rewrite the file. Messaging-platform credentials live here, and
  # losing them means registering the bot again from scratch.
  added=""
  if ! grep -q '^CUSTOM_API_KEY=' "$HERMES_HOME/.env"; then
    printf '\n# Added by setup.sh: Hermes OpenAI client refuses an empty key,\n# claude-shim ignores the value.\nCUSTOM_API_KEY=not-used-by-the-shim\n' >> "$HERMES_HOME/.env"
    added="CUSTOM_API_KEY"
  fi
  if ! grep -q '^API_SERVER_KEY=' "$HERMES_HOME/.env"; then
    printf '\n# Added by setup.sh: auth key for the Hermes gateway API on 8642.\nAPI_SERVER_KEY=%s\n' "$(gen_key)" >> "$HERMES_HOME/.env"
    added="${added:+$added }API_SERVER_KEY"
  fi
  echo "${HERMES_HOME}/.env kept as is${added:+, added missing keys: $added}"
else
  api_server_key=$(gen_key)
  cat > "$HERMES_HOME/.env" <<EOF
# Hermes secrets. Generated by setup.sh, gitignored, machine-local.

# claude-shim does not authenticate callers, but Hermes' OpenAI client refuses
# an empty key, so this needs a value -- any value.
CUSTOM_API_KEY=not-used-by-the-shim

# Auth key for the Hermes gateway API on port 8642.
API_SERVER_KEY=$api_server_key
EOF
  chmod 600 "$HERMES_HOME/.env"
  echo "generated $HERMES_HOME/.env (with a fresh API_SERVER_KEY)"
fi

# ---------------------------------------------------------------------------
say "Building and starting containers"
# ---------------------------------------------------------------------------
docker compose up -d --build

echo "waiting for claude-shim to report healthy..."
for _ in $(seq 1 30); do
  status=$(docker inspect --format '{{.State.Health.Status}}' claude-shim 2>/dev/null || echo starting)
  [ "$status" = "healthy" ] && break
  sleep 2
done
[ "${status:-}" = "healthy" ] || warn "claude-shim is not healthy yet; check: docker compose logs claude-shim"

# ---------------------------------------------------------------------------
say "Migrating config to this image's schema"
# ---------------------------------------------------------------------------
# The template carries a config version; a newer Hermes image may expect a
# newer one. `config migrate` adds missing keys without touching existing ones.
docker compose exec -T hermes hermes config migrate >/dev/null 2>&1 \
  && echo "config migrated" \
  || warn "config migrate failed (usually harmless) -- check: docker compose exec hermes hermes config check"

# ---------------------------------------------------------------------------
say "Verifying the search backend"
# ---------------------------------------------------------------------------
# ddgs is baked into the hermes image (see hermes/Dockerfile), so it survives
# container recreation. This only checks it is really there.
if docker compose exec -T hermes python3 -c 'import ddgs' >/dev/null 2>&1; then
  echo "ddgs present"
else
  warn "ddgs missing -- web_search will fall back to browser/terminal."
  warn "Rebuild the image: docker compose build --no-cache hermes"
fi

# ---------------------------------------------------------------------------
say "Checking Hermes routes through the shim"
# ---------------------------------------------------------------------------
# Only relevant when adopting an existing installation: setup.sh never
# overwrites an existing config.yaml, so a config that still points at a
# pay-per-token provider keeps working and quietly bills the old way. Nothing
# else in this script would notice, since the shim answers fine either way.
routing_ok=1
for pair in \
  "model.provider=custom" \
  "model.base_url=$SHIM_URL" \
  "delegation.provider=custom" \
  "delegation.base_url=$SHIM_URL" \
  "auxiliary.compression.provider=custom" \
  "auxiliary.compression.base_url=$SHIM_URL"
do
  key=${pair%%=*}
  want=${pair#*=}
  have=$(docker compose exec -T hermes hermes config get "$key" 2>/dev/null | tr -d '\r\n' || true)
  if [ "$have" != "$want" ]; then
    [ "$routing_ok" -eq 1 ] && warn "config does not route through claude-shim:"
    routing_ok=0
    printf '     docker compose exec hermes hermes config set %s %s\n' "$key" "$want"
  fi
done
# The provider is only half of it. A model name the shim cannot serve fails at
# call time rather than here: the shim strips any "vendor/" prefix and hands
# the rest to `claude --model`, so a model id carried over from a previous
# provider is rejected only once something actually asks a question. Only
# Anthropic models are reachable on a subscription.
for key in model.default delegation.model auxiliary.compression.model; do
  have=$(docker compose exec -T hermes hermes config get "$key" 2>/dev/null | tr -d '\r\n' || true)
  [ -n "$have" ] || continue
  case "${have##*/}" in
    claude-*|opus|sonnet|haiku|fable) ;;
    *)
      [ "$routing_ok" -eq 1 ] && warn "config does not route through claude-shim:"
      routing_ok=0
      warn "$key is \"$have\", which the shim cannot serve"
      printf '     docker compose exec hermes hermes config set %s claude-sonnet-5\n' "$key"
      ;;
  esac
done

if [ "$routing_ok" -eq 1 ]; then
  echo "model, delegation and compression all point at the shim"
else
  warn "run the commands above, then: docker compose restart hermes"
fi

# ---------------------------------------------------------------------------
say "Verifying the model backend answers"
# ---------------------------------------------------------------------------
# The Docker healthcheck only hits /health, which never touches
# authentication -- a container reports "healthy" even with a garbage token,
# and the 401 only shows up the first time someone actually chats. Make one
# real (cheap) call through the shim now so a broken token fails setup
# instead of the user's first conversation.
#
# Guarded with `|| true`: a non-zero exit from `docker compose exec` must not
# abort the script before the empty-response check below can report it.
response=$(docker compose exec -T claude-shim node -e '
fetch("http://127.0.0.1:8080/v1/chat/completions", {
  method: "POST",
  headers: { "content-type": "application/json" },
  body: JSON.stringify({
    model: "haiku",
    messages: [{ role: "user", content: "Reply with the single word OK." }],
  }),
})
  .then((r) => r.text())
  .then((text) => process.stdout.write(text))
  .catch((err) => process.stdout.write(JSON.stringify({ error: { message: String((err && err.message) || err) } })));
') || true

if [ -z "$response" ]; then
  die "model backend check produced no response -- is claude-shim running? check: docker compose logs claude-shim"
fi

if echo "$response" | grep -q '"error"'; then
  message=$(echo "$response" | grep -o '"message":"[^"]*"' | head -1 | sed -e 's/^"message":"//' -e 's/"$//')
  warn "backend said: ${message:-$response}"
  warn "a 401 with a token that looks correct usually means a wrapped paste -- recheck the token length check above."
  die "model backend check failed"
fi

# Print just the answer, not the whole completion envelope.
answer=$(echo "$response" | grep -o '"content":"[^"]*"' | head -1 | sed -e 's/^"content":"//' -e 's/"$//')
echo "model backend answered: ${answer:-ok}"

# ---------------------------------------------------------------------------
say "Done"
# ---------------------------------------------------------------------------
bind="${BIND_ADDR:-127.0.0.1}"
cat <<EOF

  Dashboard:   http://$bind:9119   (user: ${HERMES_DASHBOARD_BASIC_AUTH_USERNAME:-hermes})
  Gateway API: $bind:8642

  Talk to the agent:
    docker compose exec hermes hermes chat

  Watch which model answers and what it costs:
    docker compose logs -f claude-shim

EOF
